env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules: {
  indent: ["error", "tab"],
  no-console: 0,
  no-tabs: 0,
  no-param-reassign: 0,
  no-underscore-dangle: 0,
  func-names: 0,
  camelcase: 0
}